- name: Install python modules for creation of EC2 instances
  hosts: localhost
  become: yes
  tasks:
  - name: python 3.6
    ansible.builtin.yum:
      name: python36
      state: installed
  - name: python modules
    ansible.builtin.shell: '{{item}}'
    loop:
      - 'pip3 install botocore==1.25.0'
      - 'pip3 install boto3==1.22.0'
    vars:
      ansible_python_interpreter: /usr/bin/python3.6