- name: Install python modules for creation of EC2 instances
  hosts: localhost
  become: yes
  tasks:
  - name: python modules
    ansible.builtin.yum:
      name: '{{item}}'
      state: installed
    loop:
      - 'python36'
      - 'boto3==1.22.0'
      - 'botocore==1.25.0'