- name: User Logins and Registrations Service
  hosts: user
  become: yes
  tasks:
  - name: Setup NodeJS repos.
    ansible.builtin.shell: 'curl -sL https://rpm.nodesource.com/setup_lts.x | bash'
  
  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: present

  - name: check application User
    ansible.builtin.command: id roboshop
    register: u

  - name: Add application User if doesn't exit
    ansible.builtin.user:
      name: roboshop
    when: u.rc != 0
  
  - name: check app dir 
    ansible.builtin.stat:
      path: /app
    register: d

  - name: create app dir if doesn't exit
    ansible.builtin.file:
      path: /app
      state: dir
    when: d.stat.exits == False

  - name: download and Unrachive package user
    ansible.builtin.unarchive:
      path: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /app

  - name: download the dependencies.
    ansible.builtin.command: npm install
      args:
        chdir: /app
  
  - name: copy user.service file
    ansible.builtin.copy: 
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: Load the service
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Enable & Start user service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
  - name: Copy or setup MongoDB repo
    ansible.builtin.copy:
      src:  mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: Load Schema
    ansible.builtin.shell: 'mongo --host mongodb.devopsaws.site < /app/schema/user.js'

    
